/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface DscHguiApp {
    }
}
declare global {
    interface HTMLDscHguiAppElement extends Components.DscHguiApp, HTMLStencilElement {
    }
    var HTMLDscHguiAppElement: {
        prototype: HTMLDscHguiAppElement;
        new (): HTMLDscHguiAppElement;
    };
    interface HTMLElementTagNameMap {
        "dsc-hgui-app": HTMLDscHguiAppElement;
    }
}
declare namespace LocalJSX {
    interface DscHguiApp {
    }
    interface IntrinsicElements {
        "dsc-hgui-app": DscHguiApp;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "dsc-hgui-app": LocalJSX.DscHguiApp & JSXBase.HTMLAttributes<HTMLDscHguiAppElement>;
        }
    }
}
